defmodule TaskManager.Repo.Migrations.CreatedRegisterForOrg do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :owner_id,
          references(:users, column: :id, name: "organizations_owner_id_fkey", type: :uuid)
    end
  end

  def down do
    alter table(:organizations) do
      remove :owner_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `organizations` table without the `organizations_owner_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
