defmodule TaskManager.Repo.Migrations.AddedOrgId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "users_organization_id_fkey",
            type: :uuid
          ),
          null: false
    end
  end

  def down do
    alter table(:users) do
      remove :organization_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `users` table without the `users_organization_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
