defmodule :"Elixir.TaskManager.Repo.Migrations.Added-org-base" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organizations, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :active, :boolean
      add :max_users, :bigint
      add :plan, :text
      add :slug, :text
      add :name, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    drop table(:organizations)
  end
end